config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :thredded_post_likes do
    put "upvote", to: "post_likes#upvote"
  end
  resources :thredded_topic_likes do
    put "upvote", to: "topic_likes#upvote"
  end
  resources :users
  resources :faqs
  resources :pages
  resources :testimonials
  resources :newsbars
  resources :posts do
    put "like", to: "posts#upvote"
    resources :comments, only: [:index, :create] do 
      put "like", to: "comments#upvote"
    end
  end
  resources :media
  resources :sidebars
  resources :issues
  resources "contacts", only: [:new, :create]

  get 'welcome/index', as: :welcome

  match "/blog", to: "blog#index", :via => 'get'
  get '/comments/new/(:post_id)/(:parent_id)', to: 'comments#new', as: :new_comment
  get '/posts/send_campaign/:id', to: 'posts#send_campaign', as: :send_campaign

  match "/admin/home", to: "admin_home#index", :via => 'get'

  match "/faq", to: "faqs#listing", :via => 'get', as: :list_faq

  match '/contact',     to: 'contacts#new',             via: 'get'

  devise_for :admin, :path => '', :path_names => {  sign_in: 'admin', sign_out: 'logout_admin', sign_up: 'create_admin', password: 'password_admin', registration: 'register_admin' }, controllers: {
    sessions: 'admins/sessions', registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get 'admin', to: 'admins/sessions#new'
    get 'logout_admin', to: 'admins/sessions#destroy'
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post

	acts_as_tree order: 'created_at DESC'

	validates :author, presence: true
	validates :body, presence: true
	validates :post_id, presence: true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact from the Interwebs",
      :to => "heather.allaman@gmail.com",
      :from => %("#{name}" <#{email}>),
      :reply_to => %(<#{email}>)
    }
  end
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/medium.rb
class Medium < ActiveRecord::Base
	has_attached_file :file, styles: {  thumb: ["120x120>", :png] }, :convert_options => { :thumb => "-quality 70 -interlace Plane" }

	validates_attachment :file, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  # Only superusers can post to messageboards (all other users can comment through separate view hook)
 #  def thredded_can_write_messageboards
	#   if superuser?
	#     Thredded::Messageboard.all
	#   else
	#   	# prevent all messageboards (except with id: 999999) from being posted to by non-superusers (teachers)
 #    	Thredded::Messageboard.where(id: 999999)
 #  	end
	# end

	# def self.thredded_messageboards_writers(messageboards)
	#   # must be consistent with the #thredded_can_write_messageboards method
	#   if messageboards.length == 1 && messageboards[0].id == 999999
	#     where(superuser: true)
	#   else
	#     all
	#   end
	# end

	# def superuser 
	# 	Member.superuser
	# end

end

app/models/newsbar.rb
class Newsbar < ActiveRecord::Base
	validates :message, presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
	validates :body, presence: true

  has_attached_file :main_image, styles: { thumb: ["400x300>", :png] }, :convert_options => { :thumb => "-quality 70 -interlace Plane" }
  validates_attachment :main_image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, autosave: true, dependent: :destroy

	validates :title, presence: true
  validates :publish_date, presence: true

  has_attached_file :main_image, styles: { thumb: ["800x600>", :png] }, :convert_options => { :thumb => "-quality 70 -interlace Plane" }
  validates_attachment :main_image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	
	def self.search(search)
	  where("body LIKE ? OR title LIKE ?", "%#{search}%", "%#{search}%")
	end
end

app/models/post_like.rb
class PostLike < ActiveRecord::Base
end

app/models/sidebar.rb
class Sidebar < ActiveRecord::Base
	belongs_to :issue, foreign_key: "issue_id"

	validates :title, presence: true
	validates :link, format: { with: URI::regexp(%w(http https)),
    message: "must begin with http:// or https://" }, unless: ->(sidebar){sidebar.podcast_link_id.present?}

	#has_attached_file :image, styles: { display: ["800x600>", :png], thumb: ["300x200>", :png] }, :convert_options => { :display => "-quality 70 -interlace Plane", :thumb => "-quality 70 -interlace Plane" }
  #validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
	validates :title, presence: true
  validates :body, presence: true

  has_attached_file :image, styles: { thumb: ["400x400>", :png] }, :convert_options => { :thumb => "-quality 70 -interlace Plane" }
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/topic_like.rb
class TopicLike < ActiveRecord::Base
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:listing]

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  def listing 
    @faqs = Faq.all
  end


  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:title, :body)
    end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    if messages.is_a? String
      html = <<-HTML
        <div class="alert alert-<%= flash_class(level) %>">
          <button type="button" class="close" data-dismiss="alert">X</button>
          #{messages}
        </div>
      HTML
    end 

    html.html_safe
  end
end

app/helpers/fa_qs_helper.rb
module FaQsHelper
end

app/helpers/fridays_helper.rb
module FridaysHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/faqs/_form.html.erb
<%= simple_form_for(@faq) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, as: :summernote %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<div class="container">
	<div class="row">
		<h1>Editing Faq</h1>

			<%= render 'form' %>

			<%= link_to 'Show', @faq %> |
			<%= link_to 'Back', faqs_path %>
	</div>
</div>

app/views/faqs/index.html.erb
<div class="container">
  <div class="row">
    <h1>Listing Faqs</h1>
    <%= link_to 'New Faq', new_faq_path, class: 'btn btn-default' %>


    <table class="table">
      <thead>
        <tr>
          <th>FAQ</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @faqs.each do |faq| %>
          <tr>
            <td><h5><%= faq.title %></h5><%= strip_tags(faq.body).truncate_words(90) %></td>
            <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
            <td><%= link_to 'Delete', faq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>


  </div>
</div>

app/views/faqs/listing.html.erb
<div class="container-fluid cropped_header">
  <%= image_tag('cropped_header.png', style: 'visibility: hidden; width: 100%; height: auto;') %>
</div>
<div class="page container">
  <div class="row">
    <div class="col-xs-12">

      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <% @faqs.each do |faq| %>
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading-<%= faq.id %>">
              <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= faq.id %>" aria-expanded="true" aria-controls="collapse-<%= faq.id %>">
                  <%= faq.title %>
                </a>
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= faq.id %>" aria-expanded="true" aria-controls="collapse-<%= faq.id %>" class="pull-right">
                  <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
              </h4>
            </div>
            <div id="collapse-<%= faq.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<%= faq.id %>">
              <div class="panel-body">
                <%= faq.body.html_safe %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/faqs/new.html.erb
<div class="container">
  <div class="row">
  	<h1>New Faq</h1>

		<%= render 'form' %>

		<%= link_to 'Back', faqs_path %>
	</div>
</div>

app/views/faqs/show.html.erb
<div class="container">
  <div class="row">
		<p>
		  <strong>Title:</strong>
		  <%= @faq.title %>
		</p>

		<p>
		  <strong>Body:</strong>
		  <%= @faq.body %>
		</p>

		<%= link_to 'Edit', edit_faq_path(@faq) %> |
		<%= link_to 'Back', faqs_path %>
	</div>
</div>