config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :thredded_post_likes do
    put "upvote", to: "post_likes#upvote"
  end
  resources :thredded_topic_likes do
    put "upvote", to: "topic_likes#upvote"
  end
  resources :users
  resources :faqs
  resources :pages
  resources :testimonials
  resources :newsbars
  resources :posts do
    put "like", to: "posts#upvote"
    resources :comments, only: [:index, :create] do 
      put "like", to: "comments#upvote"
    end
  end
  resources :media
  resources :sidebars
  resources :issues
  resources "contacts", only: [:new, :create]

  get 'welcome/index', as: :welcome

  match "/blog", to: "blog#index", :via => 'get'
  get '/comments/new/(:post_id)/(:parent_id)', to: 'comments#new', as: :new_comment
  get '/posts/send_campaign/:id', to: 'posts#send_campaign', as: :send_campaign

  match "/admin/home", to: "admin_home#index", :via => 'get'

  match "/faq", to: "faqs#listing", :via => 'get', as: :list_faq

  match '/contact',     to: 'contacts#new',             via: 'get'

  devise_for :admin, :path => '', :path_names => {  sign_in: 'admin', sign_out: 'logout_admin', sign_up: 'create_admin', password: 'password_admin', registration: 'register_admin' }, controllers: {
    sessions: 'admins/sessions', registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get 'admin', to: 'admins/sessions#new'
    get 'logout_admin', to: 'admins/sessions#destroy'
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post

	acts_as_tree order: 'created_at DESC'

	validates :author, presence: true
	validates :body, presence: true
	validates :post_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:edit, :update, :destroy]

  def upvote 
    @comment = Comment.find_by_id(params[:id])
    @comment.likes = @comment.likes.present? ? @comment.likes + 1 : 1
    @comment.save
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: { count: @comment.likes, id: @comment.id } }
    end
  end  

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.hash_tree(limit_depth: 4)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new(parent_id: params[:parent_id], post_id: params[:post_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    # @comment = Comment.new(comment_params)

    # respond_to do |format|
    #   if @comment.save
    #     format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
    #     format.json { render :show, status: :created, location: @comment }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @comment.errors, status: :unprocessable_entity }
    #   end
    # end

    
    # @comment = @post.comments.create(comment_params_with_post)
    # redirect_to @post

    @post = Post.find(params[:post_id])

    if params[:comment][:parent_id].to_i > 0
      parent = Comment.find_by_id(params[:comment].delete(:parent_id))
      @comment = parent.children.build(comment_params)
    else
      @comment = @post.comments.create(comment_params_with_post)
    end

    if @comment.save
      flash[:success] = 'Your comment was successfully added!'
      redirect_to post_url(@post)
    else
      flash[:warning] = 'Please enter name and comment before posting.'
      redirect_to post_url(@post)
      #render 'new'
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :link, :body, :post_id)
    end

    def comment_params_with_post
       comment_params.merge(post: @post)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render(comment) +
          (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: "replies") : nil)
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<div class="well">
  <p class="text-muted">Added by <strong><%= comment.author %></strong>
    <%= time_ago_in_words(comment.created_at, format: '%B, %d %Y %H:%M:%S') %> ago</p>

  <blockquote>
    <p><%= comment.body %></p>
    <p>
    	<%= link_to post_comment_like_path(:post_id => comment.post_id,
    :id => comment.id, :comment_id => comment.id), class: 'like', method: :put, remote: true, data: { type: :json } do 
	    
	    	render  partial: 'posts/heart', locals: { thing_id: 'comment'+comment.id.to_s, heart_class: "purple"}

		  end %>
			<span id="likes_<%= comment.id %>" class="badge"><%= comment.likes %></span>
	</p>
  </blockquote>

  <% from_reply_form ||= nil %>
	<% unless from_reply_form %>
		<div class="panel-group" id="accordion">
		  <div class="panel panel-default">
		    <div class="panel-heading">
		      <h4 class="panel-title">
		        <a data-toggle="collapse" data-parent="#accordion" 
		          href="#collapse<%= comment.id %>">
		          Click to reply
		        </a>
		      </h4>
		    </div>
		    <div id="collapse<%= comment.id%>" class="panel-collapse collapse">
		      <div class="panel-body">
		          <%= form_for [@post, @post.comments.new] do |f| %>
		            <% if @post.comments.new.errors.any? %>
		              <div class="alert alert-danger">
		                <h4>There are <%= pluralize(@post.errors.count, "error") %>.</h4>
		                <ul>
		                  <%= @post.comments.new.errors.full_messages.each do |msg| %>
		                  <li><%= msg %></li>
		                  <% end %>
		                </ul>
		              </div>
		            <% end %>
		            <%= f.hidden_field :parent_id, :value => comment.id %>
		            <%= f.hidden_field :post_id %>

		            <%= f.label :author, "Name" %><br />
		            <%= f.text_field :author, class: 'form-control' %><br />
		            <%= f.label :link, "Link (optional)" %><br />
		            <%= f.text_field :link, class: 'form-control' %><br />
		            <%= f.label :body %>
		            <%= f.text_area :body, rows: 1, class: 'form-control', placeholder: "Enter comment body" %>
		            <div class="actions">
		              <%= f.submit "Submit Comment", class: 'btn btn-default' %>
		            </div>
		          <% end %>
		      </div>
		    </div>
		  </div> 
		</div>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', required: true %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>
<%= link_to 'New Comment', new_comment_path, class: 'btn btn-default' %>
<table class="table">
  <thead>
    <tr>
      <th>Author</th>
      <th>Link</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.link %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<% if @comment.parent %>
  <%= render 'comment', comment: @comment.parent, from_reply_form: true %>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Link:</strong>
  <%= @comment.link %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>