config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :thredded_post_likes do
    put "upvote", to: "post_likes#upvote"
  end
  resources :thredded_topic_likes do
    put "upvote", to: "topic_likes#upvote"
  end
  resources :users
  resources :faqs
  resources :pages
  resources :testimonials
  resources :newsbars
  resources :posts do
    put "like", to: "posts#upvote"
    resources :comments, only: [:index, :create] do 
      put "like", to: "comments#upvote"
    end
  end
  resources :media
  resources :sidebars
  resources :issues
  resources "contacts", only: [:new, :create]

  get 'welcome/index', as: :welcome

  match "/blog", to: "blog#index", :via => 'get'
  get '/comments/new/(:post_id)/(:parent_id)', to: 'comments#new', as: :new_comment
  get '/posts/send_campaign/:id', to: 'posts#send_campaign', as: :send_campaign

  match "/admin/home", to: "admin_home#index", :via => 'get'

  match "/faq", to: "faqs#listing", :via => 'get', as: :list_faq

  match '/contact',     to: 'contacts#new',             via: 'get'

  devise_for :admin, :path => '', :path_names => {  sign_in: 'admin', sign_out: 'logout_admin', sign_up: 'create_admin', password: 'password_admin', registration: 'register_admin' }, controllers: {
    sessions: 'admins/sessions', registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get 'admin', to: 'admins/sessions#new'
    get 'logout_admin', to: 'admins/sessions#destroy'
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, autosave: true, dependent: :destroy

	validates :title, presence: true
  validates :publish_date, presence: true

  has_attached_file :main_image, styles: { thumb: ["800x600>", :png] }, :convert_options => { :thumb => "-quality 70 -interlace Plane" }
  validates_attachment :main_image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	
	def self.search(search)
	  where("body LIKE ? OR title LIKE ?", "%#{search}%", "%#{search}%")
	end
end

app/controllers/posts_controller.rb
require 'gibbon'
require 'social_shares'

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:show, :upvote]

  def upvote 
    @post = Post.find_by_id(params[:id])
    @post.likes = @post.likes.present? ? @post.likes + 1 : 1
    @post.save
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: { count: @post.likes, id: @post.id } }
    end
  end  

  def send_campaign 
    @post = Post.find(params[:id])
    @post_body_title = '<span class="h1">'+@post.title+'</span>'+@post.body

    # API key in initializers/gibbon.rb
    gibbon = Gibbon::Request.new 

    recipients = {
      list_id: "1a93406f49"
    }
    settings = {
      subject_line: @post.title,
      title: @post.title,
      from_name: "KV",
      reply_to: "KV@aquariusnation.com"
    }

    @campaign_body = {
      type: "regular",
      recipients: recipients,
      settings: settings
    }

    @email_body = {
      template: {
        id: 153317,
        sections: {
          "std_preheader_content": @post.title,
          "std_content00": @post_body_title
        }
      }
    }

    begin
      @new_campaign = gibbon.campaigns.create(body: @campaign_body)
      @new_campaign_id = @new_campaign["id"]
      gibbon.campaigns(@new_campaign_id).content.upsert(body: @email_body)
      gibbon.campaigns(@new_campaign_id).actions.send.create

      respond_to do |format|
        format.html { redirect_to posts_path, notice: 'Sent to MailChimp list!' }
        format.json { render :index }
      end
    rescue Gibbon::MailChimpError => e
      respond_to do |format|
        format.html { redirect_to posts_path, notice: "Houston, we have a problem: #{e.message} - #{e.raw_body}" }
        format.json { render json: :index, status: :unprocessable_entity }
      end
    end

  end 

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order('publish_date DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.hash_tree(limit_depth: 4)

    @url = URI.parse(request.base_url).to_s + '/posts/' + @post.id.to_s + '?locale=en'
    @facebook_count = SocialShares.facebook @url
    @pinterest_count = SocialShares.pinterest @url
    @google_count = SocialShares.google @url
    @facebook_count ||= 0
    @pinterest_count ||= 0
    @google_count ||= 0
    @sum = @facebook_count + @pinterest_count + @google_count 

    if @post.category == 'Blog Post'
      @title = @post.title 
    else 
      @title = 'Daily Moon Vibe Reading'
    end

    @latest = Post.where(category: 'Blog Post').where('publish_date <= ? AND id != ?', Time.now, @post.id ).order("created_at DESC").limit(3)

  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.publish_date = Time.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:short_title, :title, :body, :main_image, :category, :publish_date, :likes)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/views/posts/_daily.html.erb
<div class="container">
  <div class="daily text-center">
  	<div class="col-xs-12">
    	<div class="row">
				<%= image_tag('daily_readings_symbol.png', width: 100, style: 'padding-bottom: 30px;') %>

		  	<h2>DAILY MOON VIBE READING</h2>
		  	<h4><span class="emph-day"><%= Date.today.strftime('%A') %></span><%= Date.today.strftime('%-d %B %Y') %></h4>



		  	<% 
					@daily_reading_text = strip_tags(@post.body).split('.').in_groups(2)

		      @daily_para_1 = @daily_reading_text[0].join(' ').to_s 
		      @daily_para_2 = @daily_reading_text[1].join(' ').to_s
			  %>

				<div class="entry text-left">
					<p><%= @daily_para_1.to_s + '.' if @daily_para_1.present? %></p>
				</div>

				<div class="entry text-left">
					<p><%= @daily_para_2.to_s if @daily_para_2.present? %></p>
				</div>

				<div class="entry text-left">
					<%= @post.body.html_safe %>
					<p class="text-center">		
						<%= link_to post_like_path(:post_id => @post.id,
    :id => @post.id), class: 'post-like', method: :put, remote: true, data: { type: :json } do 
    	    	render  partial: 'posts/heart', locals: { thing_id: 'post-'+@post.id.to_s, heart_class: "purple"}
				    end %>
						<span id="post-likes" class="badge"><%= @post.likes %></span>
					</p>
				</div>
				<hr class="col-xs-12" />
				<div class="share-this">
					
          <a href="http://www.facebook.com/sharer/sharer.php?u=<%=  URI.parse(request.base_url + request.original_fullpath) %>&title=<%= URI::escape(@post.title) %>" target="_blank">
              <i class="fa fa-facebook" aria-hidden="true"></i>
              <span class="count"><%= @facebook_count %></span>
          </a>
         
          <a href="http://pinterest.com/pin/create/bookmarklet/?media=<%= @post.main_image.url %>&url=<%=  URI.parse(request.base_url + request.original_fullpath) %>&is_video=false&description=<%= URI::escape(@post.title) %>" target="_blank">
              <i class="fa fa-pinterest-p" aria-hidden="true"></i>
              <span class="count"><%= @pinterest_count %></span>
          </a>
          
          <a href="https://plus.google.com/share?url=<%=  URI.parse(request.base_url + request.original_fullpath) %>" target="_blank">
             <i class="fa fa-google-plus" aria-hidden="true"></i>
             <span class="count"><%= @google_count %></span>
          </a>

          <a href="http://www.tumblr.com/share?v=3&u=<%=  URI.parse(request.base_url + request.original_fullpath) %>&t=<%= URI::escape(@post.title) %>" target="_blank">
              <i class="fa fa-tumblr" aria-hidden="true"></i>
          </a>
          <a href="http://twitter.com/intent/tweet?status=<%= URI::escape(@post.title) %>+<%=  URI.parse(request.base_url + request.original_fullpath) %>" target="_blank">
              <i class="fa fa-twitter" aria-hidden="true"></i>
          </a>
          <a href="mailto:?body=<%=  URI.parse(request.base_url + request.original_fullpath) %>" target="_blank"><i class="fa fa-envelope" aria-hidden="true"></i></a>
          <h2><%= @sum.to_s + ' shares' %></h2>
				</div> 

			</div>
		</div>
	</div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for @post, html: { multipart: true, :novalidate => true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label "Type of Post" %>
    <%= f.select :category, 
        options_for_select(['MVG Daily Reading', 'Blog Post' ], {:selected => @post.category})
    %>
  </div>

  <div class="form-inputs">
    <%= f.input :short_title, hint: 'Short title is for blog posts only' %>
    <%= f.input :title %>
    <%= f.input :publish_date, :value => @post.publish_date.strftime('%A, %B %-d, %Y %l:%M') %>
  </div>



  <div class="field">
    <%= f.input :body, as: :summernote %>  
  </div>

  <div class="field">
    <%= f.label "Image" %><br>
    <%= f.file_field :main_image %>
    <%= image_tag @post.main_image.url(:thumb) %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_heart.html.erb
<svg height="0" width="0" class="heart <%= heart_class %>">
  <defs>
    <linearGradient id="Gradient-<%= thing_id %>" x1="0" x2="0" y1="0" y2="1">
      <stop class="stop1" offset="0%"/>
      <stop class="stop2" offset="20%"/>
      <stop class="stop3" offset="40%"/>
      <stop class="stop4" offset="60%"/>
      <stop class="stop5" offset="80%"/>
      <stop class="stop6" offset="100%"/>
    </linearGradient>
   
  </defs>
  <path id="heart-icon-<%= thing_id %>" d="M16,28.261c0,0-14-7.926-14-17.046c0-9.356,13.159-10.399,14-0.454c1.011-9.938,14-8.903,14,0.454
      C30,20.335,16,28.261,16,28.261z" fill="url(#Gradient-<%= thing_id %>)"/>    

</svg>

app/views/posts/_post.html.erb
<div class="container">
	<div class="daily text-center">
	  <div class="col-xs-12 post-listing">
	  	<div class="row">
	  		<h4><%= @post.publish_date.strftime('%-d-%m-%Y') %></h4>
	      <h2><%= @post.short_title if @post.short_title.present? %></h2>
	      <div class="thumbnail">
	        <%= image_tag(@post.main_image.url(:thumb), :alt => @post.title, :class => "issue-img") if @post.main_image.present? %>
	      </div>
	    	
	    	<h3><%= @post.title %></h3>

				<%= image_tag('daily_readings_symbol.png', width: 100, style: 'padding-bottom: 30px;') %>


				<div class="entry text-left">
					<%= @post.body.html_safe %>
					<p class="text-center">		
						<%= link_to post_like_path(:post_id => @post.id,
    :id => @post.id), class: 'post-like', method: :put, remote: true, data: { type: :json } do
						 render  partial: 'posts/heart', locals: { thing_id: 'post-'+@post.id.to_s, heart_class: "purple"}
				    end %>
						<span id="post-likes" class="badge"><%= @post.likes %></span>
					</p>
				</div>
				<hr class="col-xs-12" />
				<div class="share-this">
					
          <a href="http://www.facebook.com/sharer/sharer.php?u=<%=  URI.parse(request.base_url + request.original_fullpath) %>&title=<%= URI::escape(@post.title) %>" target="_blank">
              <i class="fa fa-facebook" aria-hidden="true"></i>
              <span class="count"><%= @facebook_count %></span>
          </a>
         
          <a href="http://pinterest.com/pin/create/bookmarklet/?media=<%= @post.main_image.url %>&url=<%=  URI.parse(request.base_url + request.original_fullpath) %>&is_video=false&description=<%= URI::escape(@post.title) %>" target="_blank">
              <i class="fa fa-pinterest-p" aria-hidden="true"></i>
              <span class="count"><%= @pinterest_count %></span>
          </a>
          
          <a href="https://plus.google.com/share?url=<%=  URI.parse(request.base_url + request.original_fullpath) %>" target="_blank">
             <i class="fa fa-google-plus" aria-hidden="true"></i>
             <span class="count"><%= @google_count %></span>
          </a>

          <a href="http://www.tumblr.com/share?v=3&u=<%=  URI.parse(request.base_url + request.original_fullpath) %>&t=<%= URI::escape(@post.title) %>" target="_blank">
              <i class="fa fa-tumblr" aria-hidden="true"></i>
          </a>
          <a href="http://twitter.com/intent/tweet?status=<%= URI::escape(@post.title) %>+<%=  URI.parse(request.base_url + request.original_fullpath) %>" target="_blank">
              <i class="fa fa-twitter" aria-hidden="true"></i>
          </a>
          <a href="mailto:?body=<%=  URI.parse(request.base_url + request.original_fullpath) %>" target="_blank"><i class="fa fa-envelope" aria-hidden="true"></i></a>
          <h2><%= @sum.to_s + ' shares' %></h2>
				</div> 

				<div id="latest">
					<% @latest.each do |short| %>

					<%
            @url = URI.parse(request.base_url).to_s + '/posts/' + short.id.to_s + '?locale=en'
            
            @facebook_count = SocialShares.facebook @url
            @pinterest_count = SocialShares.pinterest @url
            @google_count = SocialShares.google @url
            @facebook_count ||= 0
            @pinterest_count ||= 0
            @google_count ||= 0
            @sum = @facebook_count + @pinterest_count + @google_count 
 
          %>

					<div class="col-xs-12 col-sm-4 short">
						<%= link_to image_tag(short.main_image.url(:thumb), :alt => short.title, :class => "thumbnail"), post_path(short) if short.main_image.present? %>
						<p><%= link_to short.title, post_path(short) %></p>
						<small><%= short.likes.present? ? short.likes.to_s + ' likes' : ' 0 likes' %></small>
						&nbsp;&middot;&nbsp;
						<small><%= @sum.to_s + ' shares' %></small>
					</div>

					<% end %>
				</div>

				
			</div>
		</div>
	</div>
</div>

app/views/posts/_post_comments.html.erb
<div class="container">
  <div class="daily">
    <div class="col-xs-12 comments-section">
      <div class="row">
        <%= comments_tree_for @comments %>
        <!-- in comments/_comment -->
      </div>
        
      <div class="row">
        <%= form_for [@post, @post.comments.new] do |f| %>
          <% if @post.comments.new.errors.any? %>
            <div class="alert alert-danger">
              <h4>There are <%= pluralize(@post.errors.count, "error") %>.</h4>
              <ul>
                <%= @post.comments.new.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <%= f.label :author, "Name" %><br />
          <%= f.text_field :author, class: 'form-control' %><br />
          <%= f.label :link, "Link (optional)" %><br />
          <%= f.text_field :link, class: 'form-control' %><br />
          <%= f.label :body %>
          <%= f.text_area :body, rows: 1, class: 'form-control', placeholder: "Enter comment body" %>
          <div class="actions">
            <%= f.submit "Submit Comment", class: 'btn btn-default' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<h1>Editing Post</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @post %> |
		<%= link_to 'Back', posts_path %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <h1>Blog Posts</h1>

    <%= link_to 'New Post', new_post_path, class: "btn btn-default" %>

    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Category</th>
          <th>Publish date</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td><%= post.category %></td>
            <td><%= post.publish_date.strftime('%A, %B %-d, %Y %l:%M') %></td>
            <td><%= link_to 'Show', post, data: { turbolinks: false } %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to_if(post.category == 'Blog Post', 'Send to MailChimp List', send_campaign_path(post.id), class: "btn btn-danger") do

              end %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<h1>New Post</h1>

		<%= render 'form' %>

		<%= link_to 'Back', posts_path %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container-fluid cropped_header">
  <%= image_tag('cropped_header.png', style: 'visibility: hidden; width: 100%; height: auto;') %>
</div>

<% if @post.category == 'MVG Daily Reading' %>
    <%= render 'posts/daily' %>
<% else %>
  <div class="container">
    <%= render 'posts/post' %>
<% end %> 

<div style="clear:both; width: 100%"></div>

<%= render 'posts/post_comments' %>