config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :thredded_post_likes do
    put "upvote", to: "post_likes#upvote"
  end
  resources :thredded_topic_likes do
    put "upvote", to: "topic_likes#upvote"
  end
  resources :users
  resources :faqs
  resources :pages
  resources :testimonials
  resources :newsbars
  resources :posts do
    put "like", to: "posts#upvote"
    resources :comments, only: [:index, :create] do 
      put "like", to: "comments#upvote"
    end
  end
  resources :media
  resources :sidebars
  resources :issues
  resources "contacts", only: [:new, :create]

  get 'welcome/index', as: :welcome

  match "/blog", to: "blog#index", :via => 'get'
  get '/comments/new/(:post_id)/(:parent_id)', to: 'comments#new', as: :new_comment
  get '/posts/send_campaign/:id', to: 'posts#send_campaign', as: :send_campaign

  match "/admin/home", to: "admin_home#index", :via => 'get'

  match "/faq", to: "faqs#listing", :via => 'get', as: :list_faq

  match '/contact',     to: 'contacts#new',             via: 'get'

  devise_for :admin, :path => '', :path_names => {  sign_in: 'admin', sign_out: 'logout_admin', sign_up: 'create_admin', password: 'password_admin', registration: 'register_admin' }, controllers: {
    sessions: 'admins/sessions', registrations: 'admins/registrations'
  }
  devise_scope :admin do
    get 'admin', to: 'admins/sessions#new'
    get 'logout_admin', to: 'admins/sessions#destroy'
  end

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
	validates :title, presence: true
  validates :body, presence: true

  has_attached_file :image, styles: { thumb: ["400x400>", :png] }, :convert_options => { :thumb => "-quality 70 -interlace Plane" }
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:title, :body, :image, :show)
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= simple_form_for(@testimonial) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, as: :summernote %>
    <div class="field">
      <%= f.label "Image" %><br>
      <%= f.file_field :image %>
      <%= image_tag @testimonial.image.url(:thumb) %>

    </div>
    
    <%= f.input :show %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<div class="container">
	<div class="row">
		<h1>Editing Testimonial</h1>

		<%= render 'form' %>
		<p>
			<%= link_to 'Show', @testimonial %> |
			<%= link_to 'Back', testimonials_path %>
		</p>
	</div>
</div>

app/views/testimonials/index.html.erb
<div class="container">
  <div class="row">
    <h1>Listing Testimonials</h1>

    <%= link_to 'New Testimonial', new_testimonial_path, class: 'btn btn-default' %>

    <table class="table">
      <thead>
        <tr>
          <th>Body</th>
          <th>Image</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @testimonials.each do |testimonial| %>
          <tr>
            <td><h5><%= testimonial.title %></h5>
            <%= testimonial.body.html_safe %></td>
            <td style="width: 100px; height: 100px; overflow: hidden;"><div class="thumbnail"><%= image_tag(testimonial.image.url(:thumb)) %></div></td>
            <td><%= testimonial.show %></td>
            <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
            <td><%= link_to 'Delete', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/testimonials/new.html.erb
<div class="container">
	<div class="row">
		<h1>New Testimonial</h1>

		<%= render 'form' %>
		<br />
		<p>
		<%= link_to 'Back', testimonials_path %>
		</p>
		<br />
	</div>
</div>

app/views/testimonials/show.html.erb
<div class="container">
	<div class="row">
		<p>
		  <strong>Title:</strong>
		  <%= @testimonial.title %>
		</p>

		<p>
		  <strong>Body:</strong>
		  <%= @testimonial.body.html_safe %>
		</p>

		<p>
		  <strong>Image:</strong>
	    <%= image_tag @testimonial.image.url(:thumb) %>
		</p>

		<p>
		  <strong>Show:</strong>
		  <%= @testimonial.show %>
		</p>

		<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
		<%= link_to 'Back', testimonials_path %>
	</div>
</div>